language: node_js
node_js:
  - "4"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install -g gulp bower karma jasmine karma-chrome-launcher karma-cli mocha phantomjs
  - npm install
  - bower install
script: gulp specs
